In [ ]:
import tensorflow as tf
A = tf.constant([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]], dtype=tf.float32)
B = tf.constant([[[13, 14, 15], [16, 17, 18]],
                     [[19, 20, 21], [22, 23, 24]]], dtype=tf.float32)

In [ ]:
shape = A.shape

In [ ]:
position_embedding = tf.Variable(tf.zeros(A.shape, dtype=tf.float32))

In [ ]:
for i in range(shape[0]):
    for j in range(shape[1]):
        if j%2 == 0:
            position_embedding[i,j,:].assign(A[i, j,:])
        else:
            position_embedding[i,j,:].assign(B[i, j,:])
print(position_embedding)

In [ ]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained("./bert_tiny")

In [ ]:
text= tokenizer.encode("这是一首简单的小情歌。哈哈哈哈。哈哈哈")
text

In [16]:
import numpy as np

# 创建一个维度为 (2, 3) 的数组
a = np.array([[1, 2, 3], [4, 5, 6]])

# 将数组扩展为形状为 (2, 3, 1) 的数组
b = np.expand_dims(a, axis=2)

# 将数组的最后一维填充 0，使其变为形状为 (2, 3, 5) 的数组
c = np.pad(b, [(0, 0), (0, 0), (0, 4)], mode='constant')
c

array([[[1, 0, 0, 0, 0],
        [2, 0, 0, 0, 0],
        [3, 0, 0, 0, 0]],

       [[4, 0, 0, 0, 0],
        [5, 0, 0, 0, 0],
        [6, 0, 0, 0, 0]]])

In [17]:
import tensorflow as tf
# 创建一个维度为 (2, 3) 的张量
a = tf.constant([[1, 2, 3], [4, 5, 6]])
a = tf.expand_dims(a, axis=2)
a = tf.pad(a, [(0,0),(0,0), (0,4)], mode='constant')
a

<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
array([[[1, 0, 0, 0, 0],
        [2, 0, 0, 0, 0],
        [3, 0, 0, 0, 0]],

       [[4, 0, 0, 0, 0],
        [5, 0, 0, 0, 0],
        [6, 0, 0, 0, 0]]])>

In [18]:
#对a沿最后一维求和
a = tf.reduce_max(a, axis=2)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [1]:
from bert4keras.tokenizers import Tokenizer
tokenizer = Tokenizer('./bert_base/vocab.txt',token_start=None, token_end=None)
token, seg = tokenizer.encode("小心我打你哟？来吧小宝贝", maxlen=10)
token

Using TensorFlow backend.


[2207, 2552, 2769, 2802, 872, 1518, 8043, 3341, 1416, 2207]

In [8]:
import bert4keras.models as tool
import tensorflow as tf
import numpy as np
bert = tool.build_transformer_model('./bert_base/bert_config.json',checkpoint_path='./bert_base/bert_model.ckpt' ,return_keras_model=True)
##创建一个(2, 3)的随机tensor
a = tf.random.uniform([2, 100])
##创建一个(2, 3)的全零tensor
b = tf.zeros_like(a)
bert([a, b])

<tf.Tensor: shape=(2, 100, 768), dtype=float32, numpy=
array([[[-0.1772466 ,  0.34175894,  0.64343834, ...,  0.41287312,
          0.09676903, -0.61870056],
        [-0.07967214,  0.4830034 ,  0.49469325, ...,  0.0173005 ,
         -0.18170899, -0.6504049 ],
        [-0.12041303,  0.43314874,  0.66853416, ..., -0.15939887,
         -0.27360514, -0.6843047 ],
        ...,
        [-0.19310185,  0.30666983,  0.76597536, ..., -0.07399194,
         -0.4595993 , -0.7638679 ],
        [-0.20193541,  0.3124683 ,  0.8203735 , ..., -0.03621854,
         -0.43797776, -0.7824234 ],
        [-0.09351825,  0.29551134,  0.8195225 , ..., -0.06353907,
         -0.42415088, -0.8495459 ]],

       [[-0.1772466 ,  0.34175894,  0.64343834, ...,  0.41287312,
          0.09676903, -0.61870056],
        [-0.07967214,  0.4830034 ,  0.49469325, ...,  0.0173005 ,
         -0.18170899, -0.6504049 ],
        [-0.12041303,  0.43314874,  0.66853416, ..., -0.15939887,
         -0.27360514, -0.6843047 ],
        ...,